name: Latest blog post workflow
on:
  workflow_dispatch:

jobs:     
  job_1:
    name: update-readme-with-blog
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: gautamkrishnar/blog-post-workflow@master
          with:
            feed_list: "https://medium.com/feed/@kaustubhgupta1828, https://www.kaustubhgupta.xyz/blog-feed.xml"
            max_post_count: 7
            readme_path: text.txt
            template: "$newline <h2 class='h2-blog'><a class='a-lightblue' href=$url>$title</a></h2>$newline <br>"
                    

       
