name: Latest portfolio
on:
  workflow_dispatch:

jobs:     
  job_1:
    name: update-index-with-project
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: kaustubhgupta/PortfolioFy@main
          with:
            gh_token: ${{ secrets.TOKEN }}
